apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # echo -n "rootpassword" | base64
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  # echo -n "userpassword" | base64
  MYSQL_PASSWORD: dXNlcnBhc3N3b3Jk
  # echo -n "myuser" | base64
  MYSQL_USER: bXl1c2Vy
